# yaml-language-server: $schema=https://raw.githubusercontent.com/sanger-tol/nf-core-modules/main/modules/environment-schema.json
---
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::bwa-mem2=2.2.1
  - bioconda::htslib=1.22.1
  - bioconda::samtools=1.22.1
