# yaml-language-server: $schema=https://raw.githubusercontent.com/sanger-tol/nf-core-modules/main/modules/environment-schema.json
---
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::htslib=1.23
  - bioconda::minimap2=2.30
  - bioconda::pyfastx=2.3.0
  - bioconda::samtools=1.23
  - conda-forge::click=8.3.0
  - conda-forge::python=3.13
