---
# yaml-language-server: $schema=https://raw.githubusercontent.com/sanger-tol/nf-core-modules/refs/heads/main/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::htslib=1.23
  - bioconda::samtools=1.23
