# yaml-language-server: $schema=https://raw.githubusercontent.com/sanger-tol/nf-core-modules/main/modules/environment-schema.json
---
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::gawk=5.3.1
