---
# yaml-language-server: $schema=https://raw.githubusercontent.com/sanger-tol/nf-core-modules/main/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::htslib=1.23
  - bioconda::samtools=1.23
  - bioconda::yahs=1.2.2
  - conda-forge::coreutils=9.5
  - conda-forge::gawk=5.3.1
