---
# yaml-language-server: $schema=https://raw.githubusercontent.com/sanger-tol/nf-core-modules/master/modules/environment-schema.json
channels:
  - conda-forge
dependencies:
  - conda-forge::coreutils=9.5

