---
# yaml-language-server: $schema=https://raw.githubusercontent.com/sanger-tol/nf-core-modules/main/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::bedtools=2.31.1
  - bioconda::htslib=1.23
  - bioconda::samtools=1.23
  - conda-forge::coreutils=9.5
